# -*- coding: utf-8 -*-
"""K-MeansClustering.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Sic1xJnE3srvlVhTvG0GbUSyP7PiE1nI

Importing Library
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
from sklearn.datasets.samples_generator import make_blobs

"""Inserting Dataset"""

Data = {'x': [32,34,27,26,28,28,27,27,33,27,20,28,25,26,28,28,34,31,33,30],
        'y': [32,30,30,28,25,26,25,24,27,27,32,34,33,32,33,32,33,29,30,27]
       }

"""Listing dataset into frame"""

df = pd.DataFrame(Data,columns=['x','y'])

"""Showing Dataset"""

print (df)

"""Converting dataset into centroids"""

kmeans = KMeans(n_clusters=3).fit(df)
centroids = kmeans.cluster_centers_
plt.scatter(df['x'], df['y'], c= kmeans.labels_.astype(float), s=50, alpha=0.5)

"""Assigning & Clustering Centroids"""

X, y_true = make_blobs(n_samples=300, centers=4, cluster_std=0.60, random_state=0)
plt.scatter(X[:, 0], X[:, 1], s=50);

kmeans = KMeans(n_clusters=4)
kmeans.fit(X)
y_kmeans = kmeans.predict(X)

plt.scatter(X[:, 0], X[:, 1], c=y_kmeans, s=50, cmap='viridis')

centers = kmeans.cluster_centers_
plt.scatter(centers[:, 0], centers[:, 1], c='black', s=200, alpha=0.5);